affinity: {}
annotations: {}
appSettings:
    configMap: blip-plugin-broadcast-staging
    path: /app/src/config/default.json
    subPath: default.json
autoscale:
  averageCPUUtilization: 60
  maxReplicas: 2
  minReplicas: 1
environment:
  stage: staging
fullnameOverride: blip-plugin-broadcast
image:
  imagePullSecretName: acr-takecustomersuccess
  pullPolicy: IfNotPresent
  repository: takecustomersuccess.azurecr.io/blip-plugin-broadcast
  tag: 6622
imagePullSecrets: []
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  enabled: true
  hostName: blip-plugin-broadcast.hmg-cs.blip.ai
  tls:
    secretName: hmg-cs.blip.ai
nodeSelector: {}
probes:
  enabled: false
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
secrets: {}
service:
  port: 80
  type: ClusterIP
team: delta
tolerations: []
